trigger: none  # Manual trigger to control deployments

parameters:
  - name: deployDev
    displayName: "Deploy to Dev?"
    type: boolean
    default: true
  - name: deployUAT
    displayName: "Deploy to UAT?"
    type: boolean
    default: true
  - name: deployProd
    displayName: "Deploy to Prod?"
    type: boolean
    default: true

variables:
  - group: Databricks_Variables  

stages:
  - stage: Build
    displayName: "Build & Publish Artifacts"
    jobs:
      - job: Databricks_CI
        displayName: "Run Databricks Build"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: PublishPipelineArtifact@1
            displayName: "Publish Repository Artifacts"
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/python_bundle_2'  
              artifact: 'python_bundle_2_artifact'
              publishLocation: 'pipeline'

  - stage: Deploy_Dev
    displayName: "Deploy to Dev"
    dependsOn: Build
    condition: eq('${{ parameters.deployDev }}', true) 
    jobs:
      - template: ../Deployment_template/deploy-template.yml
        parameters:
          environment: dev
          databricksHost: $(databricks_dev_host)
          atifactName: python_bundle_2_artifact

  - stage: Deploy_UAT
    displayName: "Deploy to UAT"
    dependsOn: Deploy_Dev
    condition: eq('${{ parameters.deployUAT }}', true) 
    jobs:
      - template: ../Deployment_template/deploy-template.yml
        parameters:
          environment: uat
          databricksHost: $(databricks_uat_host)
          atifactName: python_bundle_2_artifact

  - stage: Deploy_Prod
    displayName: "Deploy to Prod"
    dependsOn: Deploy_UAT
    condition: eq('${{ parameters.deployProd }}', true)
    jobs:
      - template: ../Deployment_template/deploy-template.yml
        parameters:
          environment: prod
          databricksHost: $(databricks_prod_host)
          atifactName: python_bundle_2_artifact
